const storage = new Storage()
const map = new Map(storage)
const canvas = new Canvas("canvas", storage)
const slide = new Slider("img_slider", "etape")
new Page1(map, storage)
new Page2(storage, canvas, map)
